import { Poppins } from "next/font/google";

import "./globals.css";

const geistMono = Poppins({
  variable: "--font-geist-mono",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
});

export const metadata = {
  title: "Car App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={` ${geistMono.variable} antialiased`}>{children}</body>
    </html>
  );
}
